apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
#nameSuffix: -dev

namespace: dev

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml

commonLabels:
  env: dev

images:
  - name: nginx
    newTag: 1.25.3
