apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: db-pod
  template:
    metadata:
      labels:
        name: db-pod
    spec:
      containers:
        - name: db-container
          image: mysql:8.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-password