apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

resources:
- ../../base
- namespace.yaml

patches:
- target:
    kind: Deployment
    name: db-deployment
  patch: |
    - op: remove
      path: /spec/template/spec/containers/0/env/0/value
    - op: add
      path: /spec/template/spec/containers/0/env/0/valueFrom
      value:
        configMapKeyRef:
            name: cm-database
            key: rootPassword

configMapGenerator:
- name: cm-database
#  options:
#    disableNameSuffixHash: true
  files:
  - rootPassword=cm/rootPassword.txt