apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  type: NodePort
  selector:
    name: db-pod
  ports:
    - name: bd-port
      protocol: TCP
      port: 3306
      targetPort: 3306