apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    owner: Eduar
  name: dev
---
apiVersion: v1
data:
  pages: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Prueba</title>
    </head>
    <body>
        <h1>Esta es una prueba de kustomize en el entorno de dev</h1>
    </body>
    </html>
  servers: |-
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }
kind: ConfigMap
metadata:
  labels:
    env: dev
    owner: Eduar
  name: dev-cm-nginx-7d7h86kf8b
  namespace: dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-service
    env: dev
    owner: Eduar
  name: dev-nginx-service
  namespace: dev
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: proxy
    env: dev
    owner: Eduar
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
    env: dev
    owner: Eduar
  name: dev-nginx-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      name: nginx-pod
      owner: Eduar
  template:
    metadata:
      labels:
        env: dev
        name: nginx-pod
        owner: Eduar
    spec:
      containers:
      - image: nginx:1.25.3
        name: nginx-container
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: cm-pages
        - mountPath: /etc/nginx/conf.d/
          name: cm-servers
      volumes:
      - configMap:
          items:
          - key: pages
            path: index.html
          name: dev-cm-nginx-7d7h86kf8b
        name: cm-pages
      - configMap:
          items:
          - key: servers
            path: nginx.conf
          name: dev-cm-nginx-7d7h86kf8b
        name: cm-servers
