apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
#nameSuffix: -dev
namespace: dev

resources:
- namespace.yaml
- ../../base

commonLabels:
  env: dev
  owner: Eduar

images:
  - name: nginx
    newTag: 1.25.3

configMapGenerator:
- name: cm-nginx
  files:
  - servers=./nginx/servers/nginx.conf
  - pages=./nginx/pages/index.html