apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pre-
namespace: pre

resources:
- namespace.yaml
- ../../base

commonLabels:
  env: pre
  owner: Eduar

patches:
- path: change-service-port.patch.yaml

images:
  - name: nginx
    newTag: 1.25.3

configMapGenerator:
- name: cm-nginx
  files:
  - servers=./nginx/servers/nginx.conf
  - pages=./nginx/pages/index.html