apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-pod
  template:
    metadata:
      labels:
        name: backend-pod
    spec:
      containers:
        - name: backend-container
          image: python:3-alpine
          command: ["sh", "-c", 'echo "Soy el backend en python del entorno $ENTORNO con el secreto $SECRET" > index.html && python -m http.server 8080']
          env:
          - name: ENTORNO
            valueFrom:
              configMapKeyRef:
                name: cm-backend
                key: entorno
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: secret-env
                key: secret
