apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  selector:
    name: backend-pod
  ports:
    - name: http-backend
      protocol: TCP
      port: 8080