apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pro-
namespace: pro

resources:
- ../../base
- namespace.yaml

patches:
- target:
    kind: Deployment
    name: db-deployment
  patch: |
    - op: remove
      path: /spec/template/spec/containers/0/env/0/value
    - op: add
      path: /spec/template/spec/containers/0/env/0/valueFrom
      value:
        secretKeyRef:
            name: pro-secret-database
            key: rootPassword

secretGenerator:
- name: secret-database
  type: Opaque
  options:
    disableNameSuffixHash: true
  files:
  - rootPassword=secret/rootPassword.txt