apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy-service
spec:
  type: NodePort
  selector:
    name: proxy-pod
  ports:
    - name: https-proxy
      protocol: TCP
      port: 443