apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx-pod
  template:
    metadata:
      labels:
        name: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.0
          volumeMounts:
            - name: cm-pages
              mountPath: /usr/share/nginx/html/
            - name: cm-servers
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: cm-pages
          configMap:
            name: cm-nginx
            items:
              - key: pages
                path: index.html
        - name: cm-servers
          configMap:
            name: cm-nginx
            items:
              - key: servers
                path: nginx.conf