apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: proxy-service
spec:
  type: NodePort
  selector:
    app: proxy 
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30419
