apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pro-
namespace: pro

resources:
- namespace.yaml
- ../../base

replicas:
- name: nginx-deployment
  count: 4

commonLabels:
  env: pre
  owner: Eduar

images:
  - name: nginx
    newTag: 1.25.3

configMapGenerator:
- name: cm-nginx
  files:
  - servers=./nginx/servers/nginx.conf
  - pages=./nginx/pages/index.html